### ISSUE TITLE
docker registry images for container runtimes

### ISSUE THREAD

**Issue by cfi2017** [SudhanPlayz/Discord-MusicBot#1049]
Running the bot on a container runtime is currently provided through a limiting docker-compose file. This requires pulling the source repository and building the containers from source and restricts you to a docker-compose supported container runtime. 

A previous proposal to properly provide containerise the services exists: #586 – This proposal was shut down with the comment that the provided docker-compose file is "good enough". 

In a production grade container runtime environment, build tools are often not - and should often not be - available. Running the application through say a Kubernetes cluster requires images to be available in a container registry. 

**Describe the ideal solution**
Ideally, images should be provided with each release in a highly available container registry such as docker hub, the Github container registry (ghcr.io) or the Google container registry (gcr.io). The Github container registry is a decent choice here due to the availability of a proper CI workflow through Github actions and the immediate integration of the container registry into the repository. Additionally, the docker hub registry comes with public API limits that can be difficult to work with.

As LavaLink is already available as a docker image, only the actual Musicbot needs to be built. 

**Describe alternatives you've considered**
I briefly considered pushing my own images to a registry, but I dislike that notion as it comes with added maintenance effort that could be much simplified with a proper CI on the root repository (see below). I would be more than willing to contribute to a proper CI and also to additional resources like Kubernetes configurations or a Helm chart for the application. 

**Additional context**

A sample github actions workflow to properly deploy the docker image to the github container registry would be:
```yaml
name: Docker Image CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0
      name: Check out code
    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build and Push image
      with:
        image: SudhanPlayz/Discord-MusicBot
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```
